services:
  nginx:
    image: nginx:1.25.5
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - core1
      - core2

  core1:
    build:
      context: ./core
    working_dir: /app

  core2:
    build:
      context: ./core
    working_dir: /app
